# Generated by Django 5.1.6 on 2025-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitem",
            name="location_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
