# Generated by Django 5.1.6 on 2025-03-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0001_initial_sde_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingEntryType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name_id", models.IntegerField()),
                ("name", models.TextField()),
                ("name_translation", models.TextField()),
                ("description", models.TextField()),
                ("journal_message_id", models.IntegerField(default=None, null=True)),
                ("message_id", models.IntegerField(default=None, null=True)),
                ("message_translation", models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CloneState",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("skills", models.JSONField(default=dict)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CompressibleType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Debuff",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name_id", models.IntegerField(default=None, null=True)),
                ("location_group_modifiers", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("operation_name", models.TextField()),
                ("location_modifiers", models.JSONField(default=list)),
                ("location_required_skill_modifiers", models.JSONField(default=list)),
                ("item_modifiers", models.JSONField(default=list)),
                ("aggregate_mode", models.TextField()),
                ("show_output_value_in_ui", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DogmaEffectCategory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DogmaUnit",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(default=None, null=True)),
                ("display_name", models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicItemAttribute",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("input_output_mapping", models.JSONField(default=list)),
                ("attribute_ids", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ExpertSystem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("hidden", models.BooleanField()),
                ("duration_days", models.IntegerField()),
                ("skills_granted", models.JSONField(default=dict)),
                ("associated_ship_types", models.JSONField(default=list)),
                ("retired", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="HoboleaksStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.TextField()),
                ("deprecated", models.BooleanField()),
                ("stale", models.BooleanField()),
                ("md5", models.TextField()),
                ("revision", models.IntegerField()),
                ("import_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndustryActivity",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IndustryAssemblyLine",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("activity_id", models.IntegerField()),
                ("base_material_multiplier", models.FloatField()),
                ("base_time_multiplier", models.FloatField()),
                ("details_per_group", models.JSONField(default=list)),
                ("details_per_category", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="IndustryInstallationType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("assembly_lines", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="IndustryModifier",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "manufacturing",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "research_material",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "research_time",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("invention", models.JSONField(blank=True, default=dict, null=True)),
                ("copying", models.JSONField(blank=True, default=dict, null=True)),
                ("reaction", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndustryTargetFilter",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("category_ids", models.JSONField(default=list)),
                ("group_ids", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="RepackagedVolume",
            fields=[
                ("item_id", models.IntegerField(primary_key=True, serialize=False)),
                ("volume", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("corporation_id", models.IntegerField()),
                ("career_id", models.IntegerField()),
                ("race_id", models.IntegerField()),
                ("name", models.TextField(default=None, null=True)),
                ("internal_name", models.TextField(default=None, null=True)),
                ("icon_id", models.IntegerField(default=None, null=True)),
                ("description", models.TextField()),
                ("starting_stations", models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolMap",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("school_id", models.IntegerField()),
                ("solar_system_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SkillPlan",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("internal_name", models.TextField()),
                ("milestones", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("career_path_id", models.IntegerField(default=None, null=True)),
                ("skill_requirements", models.JSONField(default=list)),
                ("faction_id", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypeMaterial",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("materials", models.JSONField(default=list)),
            ],
        ),
    ]
