# Generated by Django 5.1.6 on 2025-03-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="name",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
