# Generated by Django 5.1.6 on 2025-03-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0002_alter_invitem_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitem",
            name="item_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
