# Generated by Django 5.1.6 on 2025-03-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0002_constellation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constellation",
            name="radius",
            field=models.FloatField(default=None, null=True),
        ),
    ]
