# Generated by Django 5.1.6 on 2025-03-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0003_alter_constellation_radius"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solarsystem",
            name="solar_system_name_id",
        ),
    ]
