# Generated by Django 5.1.6 on 2025-03-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0003_alter_invitem_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitem",
            name="flag_id",
        ),
        migrations.RemoveField(
            model_name="invitem",
            name="item_id",
        ),
        migrations.RemoveField(
            model_name="invname",
            name="item_id",
        ),
        migrations.RemoveField(
            model_name="invposition",
            name="item_id",
        ),
        migrations.RemoveField(
            model_name="invuniquename",
            name="item_id",
        ),
    ]
