# Generated by Django 5.1.6 on 2025-03-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0004_remove_invitem_flag_id_remove_invitem_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ancestry",
            name="short_description",
            field=models.TextField(default=None, null=True),
        ),
    ]
