# Generated by Django 5.1.6 on 2025-03-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0004_remove_solarsystem_solar_system_name_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarsystem",
            name="star_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
