# Generated by Django 5.1.6 on 2025-03-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0005_alter_solarsystem_star_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solarsystem",
            name="solar_system_id",
        ),
    ]
