# Generated by Django 5.1.6 on 2025-03-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0006_remove_solarsystem_solar_system_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarsystem",
            name="sun_type_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
