# Generated by Django 5.1.6 on 2025-03-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0006_alter_dogmaattributecategory_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogmaattribute",
            name="attribute_id",
        ),
    ]
