# Generated by Django 5.1.6 on 2025-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0007_remove_dogmaattribute_attribute_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogmaattribute",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
    ]
