# Generated by Django 5.1.6 on 2025-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0007_alter_solarsystem_sun_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stargate",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type_id", models.IntegerField()),
                ("position", models.JSONField(default=list)),
                ("destination", models.IntegerField()),
                ("solar_system_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="solarsystem",
            name="secondary_sun",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
