# Generated by Django 5.1.6 on 2025-03-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0008_alter_dogmaattribute_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogmaeffect",
            name="guid",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="dogmaeffect",
            name="sfx_name",
            field=models.TextField(default=None, null=True),
        ),
    ]
