# Generated by Django 5.1.6 on 2025-03-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0008_stargate_solarsystem_secondary_sun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moon",
            name="celestial_index",
        ),
    ]
