# Generated by Django 5.1.6 on 2025-03-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0009_alter_dogmaeffect_guid_alter_dogmaeffect_sfx_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="flat_logo",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="faction",
            name="flat_logo_with_name",
            field=models.TextField(default=None, null=True),
        ),
    ]
