# Generated by Django 5.1.6 on 2025-03-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0010_alter_faction_flat_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphicid",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="graphicid",
            name="graphic_file",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="graphicid",
            name="sof_faction_name",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="graphicid",
            name="sof_hull_name",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="graphicid",
            name="sof_race_name",
            field=models.TextField(default=None, null=True),
        ),
    ]
