# Generated by Django 5.1.6 on 2025-03-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0011_alter_graphicid_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iconid",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="metagroup",
            name="icon_suffix",
            field=models.TextField(default=None, null=True),
        ),
    ]
