# Generated by Django 5.1.6 on 2025-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0012_alter_iconid_description_alter_metagroup_icon_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npccorporation",
            name="url",
            field=models.TextField(default=None, null=True),
        ),
    ]
