# Generated by Django 5.1.6 on 2025-03-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0013_alter_npccorporation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npccorporationdivision",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
    ]
