# Generated by Django 5.1.6 on 2025-03-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0015_alter_npccorporation_shares"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="station_id",
        ),
    ]
