# Generated by Django 5.1.6 on 2025-03-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0016_remove_station_station_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skin",
            name="skin_description",
            field=models.TextField(default=None, null=True),
        ),
    ]
