# Generated by Django 5.1.6 on 2025-03-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0017_alter_skin_skin_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="sof_faction_name",
            field=models.TextField(default=None, null=True),
        ),
    ]
