from django.db import models


class NPCCorporation(models.Model):
    id = models.IntegerField(primary_key=True)
    allowed_member_races = models.JSONField(null=True, blank=True, default=list)
    ceo_id = models.IntegerField()
    corporation_trades = models.JSONField(null=True, blank=True, default=dict)
    deleted = models.BooleanField(default=False)
    description = models.TextField()
    divisions = models.JSONField(null=True, blank=True, default=dict)
    enemy_id = models.IntegerField()
    exchange_rates = models.JSONField(null=True, blank=True, default=dict)
    extent = models.CharField(max_length=2)
    faction_id = models.IntegerField()
    friend_id = models.IntegerField()
    has_player_personnel_manager = models.BooleanField(default=False)
    icon_id = models.IntegerField()
    initial_price = models.IntegerField()
    investors = models.JSONField(null=True, blank=True, default=dict)
    lp_offer_tables = models.JSONField(null=True, blank=True, default=list)
    main_activity_id = models.IntegerField()
    member_limit = models.IntegerField()
    minimum_join_standing = models.IntegerField()
    min_security = models.FloatField()
    name = models.TextField()
    public_shares = models.IntegerField()
    race_id = models.IntegerField()
    secondary_activity_id = models.IntegerField()
    send_char_termination_message = models.BooleanField(default=False)
    shares = models.IntegerField()
    size = models.CharField(max_length=1)
    size_factor = models.FloatField()
    solar_system_id = models.IntegerField()
    station_id = models.IntegerField()
    tax_rate = models.FloatField()
    ticker_name = models.CharField(max_length=10)
    unique_name = models.BooleanField(default=True)
    url = models.TextField(null=True, blank=True, default=None)
