name: Run Linters

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          cache: 'pip'

      - name: Install python packages
        run: pip install djlint django-upgrade

      - name: Run ruff
        uses: astral-sh/ruff-action@v3.2.2
        continue-on-error: true

      - name: Run django-upgrade
        run: django-upgrade --target-version 5.2
        continue-on-error: true

      - name: Run djlint --lint
        run: djlint . --lint
        continue-on-error: true

      - name: Run djlint --check
        run: djlint . --check
        continue-on-error: true
